# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Docs/UI/NovoFornecedor.ui'
#
# Created: Wed Apr  6 04:49:26 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_NovoFornecedor(object):
    def setupUi(self, NovoFornecedor):
        NovoFornecedor.setObjectName(_fromUtf8("NovoFornecedor"))
        NovoFornecedor.resize(823, 715)
        NovoFornecedor.move(550, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Icons/mdpi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NovoFornecedor.setWindowIcon(icon)
        self.label_8 = QtGui.QLabel(NovoFornecedor)
        self.label_8.setGeometry(QtCore.QRect(430, 40, 71, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tbNome = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbNome.setGeometry(QtCore.QRect(90, 30, 291, 31))
        self.tbNome.setObjectName(_fromUtf8("tbNome"))
        self.btnSalvar = QtGui.QPushButton(NovoFornecedor)
        self.btnSalvar.setGeometry(QtCore.QRect(710, 680, 101, 27))
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.tbDescricao = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbDescricao.setGeometry(QtCore.QRect(510, 30, 291, 31))
        self.tbDescricao.setObjectName(_fromUtf8("tbDescricao"))
        self.btnCancelar = QtGui.QPushButton(NovoFornecedor)
        self.btnCancelar.setGeometry(QtCore.QRect(580, 680, 101, 27))
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.label_7 = QtGui.QLabel(NovoFornecedor)
        self.label_7.setGeometry(QtCore.QRect(30, 40, 51, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tbEndereco = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbEndereco.setGeometry(QtCore.QRect(510, 80, 291, 31))
        self.tbEndereco.setObjectName(_fromUtf8("tbEndereco"))
        self.label_9 = QtGui.QLabel(NovoFornecedor)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 51, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tbCidade = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbCidade.setGeometry(QtCore.QRect(90, 80, 291, 31))
        self.tbCidade.setObjectName(_fromUtf8("tbCidade"))
        self.label_10 = QtGui.QLabel(NovoFornecedor)
        self.label_10.setGeometry(QtCore.QRect(430, 90, 71, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(NovoFornecedor)
        self.label_11.setGeometry(QtCore.QRect(30, 140, 51, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tbBairro = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbBairro.setGeometry(QtCore.QRect(90, 130, 291, 31))
        self.tbBairro.setObjectName(_fromUtf8("tbBairro"))
        self.label_12 = QtGui.QLabel(NovoFornecedor)
        self.label_12.setGeometry(QtCore.QRect(440, 150, 61, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tbNumero = QtGui.QPlainTextEdit(NovoFornecedor)
        self.tbNumero.setGeometry(QtCore.QRect(510, 140, 291, 31))
        self.tbNumero.setObjectName(_fromUtf8("tbNumero"))
        self.groupBox = QtGui.QGroupBox(NovoFornecedor)
        self.groupBox.setGeometry(QtCore.QRect(10, 190, 801, 241))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btnTelefoneRemove = QtGui.QPushButton(self.groupBox)
        self.btnTelefoneRemove.setGeometry(QtCore.QRect(740, 210, 61, 27))
        self.btnTelefoneRemove.setObjectName(_fromUtf8("btnTelefoneRemove"))
        self.tblTelefone = QtGui.QTableWidget(self.groupBox)
        self.tblTelefone.setGeometry(QtCore.QRect(420, 20, 381, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblTelefone.sizePolicy().hasHeightForWidth())
        self.tblTelefone.setSizePolicy(sizePolicy)
        self.tblTelefone.setMaximumSize(QtCore.QSize(541, 192))
        self.tblTelefone.setAutoFillBackground(False)
        self.tblTelefone.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblTelefone.setFrameShadow(QtGui.QFrame.Sunken)
        self.tblTelefone.setLineWidth(1)
        self.tblTelefone.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblTelefone.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblTelefone.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblTelefone.setShowGrid(True)
        self.tblTelefone.setGridStyle(QtCore.Qt.SolidLine)
        self.tblTelefone.setWordWrap(True)
        self.tblTelefone.setCornerButtonEnabled(True)
        self.tblTelefone.setObjectName(_fromUtf8("tblTelefone"))
        self.tblTelefone.setColumnCount(3)
        self.tblTelefone.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTelefone.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTelefone.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblTelefone.setHorizontalHeaderItem(2, item)
        self.tblTelefone.horizontalHeader().setVisible(True)
        self.tblTelefone.horizontalHeader().setCascadingSectionResizes(False)
        self.tblTelefone.horizontalHeader().setDefaultSectionSize(126)
        self.tblTelefone.horizontalHeader().setSortIndicatorShown(False)
        self.tblTelefone.horizontalHeader().setStretchLastSection(False)
        self.tblTelefone.verticalHeader().setVisible(False)
        self.tblTelefone.verticalHeader().setHighlightSections(True)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(20, 30, 321, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(130, 30, 61, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tbTelefoneDDD = QtGui.QPlainTextEdit(self.frame)
        self.tbTelefoneDDD.setGeometry(QtCore.QRect(50, 20, 51, 31))
        self.tbTelefoneDDD.setObjectName(_fromUtf8("tbTelefoneDDD"))
        self.btnTelefoneAdd = QtGui.QPushButton(self.frame)
        self.btnTelefoneAdd.setGeometry(QtCore.QRect(250, 130, 41, 27))
        self.btnTelefoneAdd.setObjectName(_fromUtf8("btnTelefoneAdd"))
        self.tbTelefoneNumero = QtGui.QPlainTextEdit(self.frame)
        self.tbTelefoneNumero.setGeometry(QtCore.QRect(200, 20, 91, 31))
        self.tbTelefoneNumero.setObjectName(_fromUtf8("tbTelefoneNumero"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tbTelefoneReferencia = QtGui.QPlainTextEdit(self.frame)
        self.tbTelefoneReferencia.setGeometry(QtCore.QRect(100, 70, 191, 31))
        self.tbTelefoneReferencia.setObjectName(_fromUtf8("tbTelefoneReferencia"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_2 = QtGui.QGroupBox(NovoFornecedor)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 430, 801, 241))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnEmailRemove = QtGui.QPushButton(self.groupBox_2)
        self.btnEmailRemove.setGeometry(QtCore.QRect(740, 210, 61, 27))
        self.btnEmailRemove.setObjectName(_fromUtf8("btnEmailRemove"))
        self.tblEmail = QtGui.QTableWidget(self.groupBox_2)
        self.tblEmail.setGeometry(QtCore.QRect(420, 20, 381, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblEmail.sizePolicy().hasHeightForWidth())
        self.tblEmail.setSizePolicy(sizePolicy)
        self.tblEmail.setMaximumSize(QtCore.QSize(541, 192))
        self.tblEmail.setAutoFillBackground(False)
        self.tblEmail.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblEmail.setFrameShadow(QtGui.QFrame.Sunken)
        self.tblEmail.setLineWidth(1)
        self.tblEmail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblEmail.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblEmail.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblEmail.setShowGrid(True)
        self.tblEmail.setGridStyle(QtCore.Qt.SolidLine)
        self.tblEmail.setWordWrap(True)
        self.tblEmail.setCornerButtonEnabled(True)
        self.tblEmail.setObjectName(_fromUtf8("tblEmail"))
        self.tblEmail.setColumnCount(2)
        self.tblEmail.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblEmail.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblEmail.setHorizontalHeaderItem(1, item)
        self.tblEmail.horizontalHeader().setVisible(True)
        self.tblEmail.horizontalHeader().setCascadingSectionResizes(False)
        self.tblEmail.horizontalHeader().setDefaultSectionSize(190)
        self.tblEmail.horizontalHeader().setSortIndicatorShown(False)
        self.tblEmail.horizontalHeader().setStretchLastSection(False)
        self.tblEmail.verticalHeader().setVisible(False)
        self.tblEmail.verticalHeader().setHighlightSections(True)
        self.frame_2 = QtGui.QFrame(self.groupBox_2)
        self.frame_2.setGeometry(QtCore.QRect(20, 30, 321, 171))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.tbEmail = QtGui.QPlainTextEdit(self.frame_2)
        self.tbEmail.setGeometry(QtCore.QRect(100, 20, 191, 31))
        self.tbEmail.setObjectName(_fromUtf8("tbEmail"))
        self.btnEmailAdd = QtGui.QPushButton(self.frame_2)
        self.btnEmailAdd.setGeometry(QtCore.QRect(250, 130, 41, 27))
        self.btnEmailAdd.setObjectName(_fromUtf8("btnEmailAdd"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(50, 30, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tbEmailReferencia = QtGui.QPlainTextEdit(self.frame_2)
        self.tbEmailReferencia.setGeometry(QtCore.QRect(100, 70, 191, 31))
        self.tbEmailReferencia.setObjectName(_fromUtf8("tbEmailReferencia"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))

        self.retranslateUi(NovoFornecedor)
        QtCore.QMetaObject.connectSlotsByName(NovoFornecedor)

    def retranslateUi(self, NovoFornecedor):
        NovoFornecedor.setWindowTitle(_translate("NovoFornecedor", "Novo Fornecedor", None))
        self.label_8.setText(_translate("NovoFornecedor", "Descrição:", None))
        self.btnSalvar.setText(_translate("NovoFornecedor", "Salvar", None))
        self.btnCancelar.setText(_translate("NovoFornecedor", "Cancelar", None))
        self.label_7.setText(_translate("NovoFornecedor", "Nome:", None))
        self.label_9.setText(_translate("NovoFornecedor", "Cidade:", None))
        self.label_10.setText(_translate("NovoFornecedor", "Endereço:", None))
        self.label_11.setText(_translate("NovoFornecedor", "Bairro:", None))
        self.label_12.setText(_translate("NovoFornecedor", "Numero:", None))
        self.groupBox.setTitle(_translate("NovoFornecedor", "Telefone", None))
        self.btnTelefoneRemove.setText(_translate("NovoFornecedor", "Remove", None))
        self.tblTelefone.setSortingEnabled(False)
        item = self.tblTelefone.horizontalHeaderItem(0)
        item.setText(_translate("NovoFornecedor", "DDD", None))
        item = self.tblTelefone.horizontalHeaderItem(1)
        item.setText(_translate("NovoFornecedor", "Numero", None))
        item = self.tblTelefone.horizontalHeaderItem(2)
        item.setText(_translate("NovoFornecedor", "Referencia", None))
        self.label_13.setText(_translate("NovoFornecedor", "Numero:", None))
        self.btnTelefoneAdd.setText(_translate("NovoFornecedor", "Add", None))
        self.label_14.setText(_translate("NovoFornecedor", "DDD:", None))
        self.label_15.setText(_translate("NovoFornecedor", "Referência:", None))
        self.groupBox_2.setTitle(_translate("NovoFornecedor", "Email", None))
        self.btnEmailRemove.setText(_translate("NovoFornecedor", "Remove", None))
        self.tblEmail.setSortingEnabled(False)
        item = self.tblEmail.horizontalHeaderItem(0)
        item.setText(_translate("NovoFornecedor", "Email", None))
        item = self.tblEmail.horizontalHeaderItem(1)
        item.setText(_translate("NovoFornecedor", "Referencia", None))
        self.btnEmailAdd.setText(_translate("NovoFornecedor", "Add", None))
        self.label_17.setText(_translate("NovoFornecedor", "Email:", None))
        self.label_18.setText(_translate("NovoFornecedor", "Referência:", None))

