# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Docs/UI/NovoPedido.ui'
#
# Created: Wed Apr  6 06:05:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_NovoPedido(object):
    def setupUi(self, NovoPedido):
        NovoPedido.setObjectName(_fromUtf8("NovoPedido"))
        NovoPedido.resize(743, 345)
        NovoPedido.move(550, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Icons/mdpi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NovoPedido.setWindowIcon(icon)
        self.notaFiscalLabel = QtGui.QLabel(NovoPedido)
        self.notaFiscalLabel.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.notaFiscalLabel.setObjectName(_fromUtf8("notaFiscalLabel"))
        self.label_2 = QtGui.QLabel(NovoPedido)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 111, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(NovoPedido)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(NovoPedido)
        self.label_5.setGeometry(QtCore.QRect(250, 310, 41, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(NovoPedido)
        self.label_6.setGeometry(QtCore.QRect(220, 270, 66, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cbTransportadora = QtGui.QComboBox(NovoPedido)
        self.cbTransportadora.setGeometry(QtCore.QRect(550, 10, 171, 31))
        self.cbTransportadora.setObjectName(_fromUtf8("cbTransportadora"))
        self.tbFrete = QtGui.QPlainTextEdit(NovoPedido)
        self.tbFrete.setGeometry(QtCore.QRect(100, 260, 91, 31))
        self.tbFrete.setPlainText(_fromUtf8(""))
        self.tbFrete.setObjectName(_fromUtf8("tbFrete"))
        self.tbDesconto = QtGui.QPlainTextEdit(NovoPedido)
        self.tbDesconto.setGeometry(QtCore.QRect(300, 260, 91, 31))
        self.tbDesconto.setObjectName(_fromUtf8("tbDesconto"))
        self.lbTotal = QtGui.QLabel(NovoPedido)
        self.lbTotal.setGeometry(QtCore.QRect(300, 310, 91, 17))
        self.lbTotal.setText(_fromUtf8(""))
        self.lbTotal.setObjectName(_fromUtf8("lbTotal"))
        self.tbNota = QtGui.QPlainTextEdit(NovoPedido)
        self.tbNota.setGeometry(QtCore.QRect(100, 10, 291, 31))
        self.tbNota.setObjectName(_fromUtf8("tbNota"))
        self.btnSalvar = QtGui.QPushButton(NovoPedido)
        self.btnSalvar.setGeometry(QtCore.QRect(620, 300, 101, 27))
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnCancelar = QtGui.QPushButton(NovoPedido)
        self.btnCancelar.setGeometry(QtCore.QRect(490, 300, 101, 27))
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.tblItem = QtGui.QTableWidget(NovoPedido)
        self.tblItem.setGeometry(QtCore.QRect(10, 50, 381, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItem.sizePolicy().hasHeightForWidth())
        self.tblItem.setSizePolicy(sizePolicy)
        self.tblItem.setMaximumSize(QtCore.QSize(541, 192))
        self.tblItem.setAutoFillBackground(False)
        self.tblItem.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tblItem.setFrameShadow(QtGui.QFrame.Sunken)
        self.tblItem.setLineWidth(1)
        self.tblItem.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblItem.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblItem.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblItem.setShowGrid(True)
        self.tblItem.setGridStyle(QtCore.Qt.SolidLine)
        self.tblItem.setWordWrap(True)
        self.tblItem.setCornerButtonEnabled(True)
        self.tblItem.setObjectName(_fromUtf8("tblItem"))
        self.tblItem.setColumnCount(3)
        self.tblItem.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(2, item)
        self.tblItem.horizontalHeader().setVisible(True)
        self.tblItem.horizontalHeader().setCascadingSectionResizes(False)
        self.tblItem.horizontalHeader().setDefaultSectionSize(126)
        self.tblItem.horizontalHeader().setSortIndicatorShown(False)
        self.tblItem.horizontalHeader().setStretchLastSection(False)
        self.tblItem.verticalHeader().setVisible(False)
        self.tblItem.verticalHeader().setHighlightSections(True)
        self.frame = QtGui.QFrame(NovoPedido)
        self.frame.setGeometry(QtCore.QRect(400, 70, 321, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(190, 90, 41, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tbQtd = QtGui.QPlainTextEdit(self.frame)
        self.tbQtd.setGeometry(QtCore.QRect(120, 80, 51, 31))
        self.tbQtd.setObjectName(_fromUtf8("tbQtd"))
        self.cbItem = QtGui.QComboBox(self.frame)
        self.cbItem.setGeometry(QtCore.QRect(100, 20, 121, 27))
        self.cbItem.setObjectName(_fromUtf8("cbItem"))
        self.btnAdd = QtGui.QPushButton(self.frame)
        self.btnAdd.setGeometry(QtCore.QRect(250, 130, 41, 27))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.tbValor = QtGui.QPlainTextEdit(self.frame)
        self.tbValor.setGeometry(QtCore.QRect(240, 80, 51, 31))
        self.tbValor.setObjectName(_fromUtf8("tbValor"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 91, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnRemove = QtGui.QPushButton(NovoPedido)
        self.btnRemove.setGeometry(QtCore.QRect(330, 230, 61, 27))
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.btnCalcular = QtGui.QPushButton(NovoPedido)
        self.btnCalcular.setGeometry(QtCore.QRect(20, 300, 71, 27))
        self.btnCalcular.setObjectName(_fromUtf8("btnCalcular"))

        self.retranslateUi(NovoPedido)
        QtCore.QMetaObject.connectSlotsByName(NovoPedido)

    def retranslateUi(self, NovoPedido):
        NovoPedido.setWindowTitle(_translate("NovoPedido", "Novo Pedido", None))
        self.notaFiscalLabel.setText(_translate("NovoPedido", "Nota Fiscal:", None))
        self.label_2.setText(_translate("NovoPedido", "Transportadora:", None))
        self.label_4.setText(_translate("NovoPedido", "Valor Frete:", None))
        self.label_5.setText(_translate("NovoPedido", "Total:", None))
        self.label_6.setText(_translate("NovoPedido", "Desconto:", None))
        self.btnSalvar.setText(_translate("NovoPedido", "Salvar", None))
        self.btnCancelar.setText(_translate("NovoPedido", "Cancelar", None))
        self.tblItem.setSortingEnabled(False)
        item = self.tblItem.horizontalHeaderItem(0)
        item.setText(_translate("NovoPedido", "Produto", None))
        item = self.tblItem.horizontalHeaderItem(1)
        item.setText(_translate("NovoPedido", "Quantidade", None))
        item = self.tblItem.horizontalHeaderItem(2)
        item.setText(_translate("NovoPedido", "Valor", None))
        self.label_8.setText(_translate("NovoPedido", "Valor:", None))
        self.btnAdd.setText(_translate("NovoPedido", "Add", None))
        self.label_7.setText(_translate("NovoPedido", "Quantidade:", None))
        self.label_3.setText(_translate("NovoPedido", "Novo Item:", None))
        self.btnRemove.setText(_translate("NovoPedido", "Remove", None))
        self.btnCalcular.setText(_translate("NovoPedido", "Calcular", None))

